name: CI

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  RUSTFLAGS: -D warnings
  RUST_BACKTRACE: short
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Show Active Rust Toolchain
      run: rustup show active-toolchain

    - name: Run cargo test
      run: cargo test --verbose --workspace

  clippy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run clippy
      run: cargo clippy -- -D clippy::all

  cargo-fmt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run cargo fmt
      run: cargo fmt --all -- --check
