name: Release-plz

on:
  push:
    branches:
      - master

permissions: {}

jobs:
  validate:
    uses: ./.github/workflows/ci.yml
    permissions:
      contents: read

  release:
    needs: validate
    uses: near/shared-workflows/.github/workflows/release-plz.yml@v1
    permissions:
      contents: write
      pull-requests: write
      id-token: write
      attestations: write
    secrets:
      pr-token: ${{ secrets.NEARPROTOCOL_CI_PR_ACCESS }}
